project:
  type: book
  output-dir: _book
  resources:
  - "/.nojekyll"

book:
  title: "SDM-book"
  subtitle: "Species Distribution Modeling with MarineBON"
  author: "Ben Best"
  repo-url: https://github.com/marinebon/sdm-book
  reader-mode: true
  repo-actions: [edit]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  google-analytics: "G-V3HZN14Z8G"
  page-navigation: true
  page-footer:
    left: |
      Website created by Ben Best, with attribution to external content
    right: |
      This book was built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - part: experiments.qmd
      chapters:
        - experiments/am-fine.qmd
    - references.qmd
  appendices:
    - glossary.qmd

bibliography: references.bib

filters:
 - lightbox
lightbox: auto

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    mermaid:
      theme: neutral
    theme:
      dark: darkly
      light: flatly
    css: glossary.css

  pdf:
    documentclass: scrreprt

editor: visual

