project:
  type: book
  output-dir: _book
  # type: website
  # output-dir: _site
  resources:
    - /.nojekyll

book:
  title: "SDM-book"
  subtitle: "Species Distribution Modeling with MarineBON"
  author: "Ben Best"
  repo-url: https://github.com/marinebon/sdm-book
  reader-mode: true
  repo-actions: [edit]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  google-analytics: "G-V3HZN14Z8G"
  page-navigation: true
  page-footer:
    left: |
      Website created by Ben Best, with attribution to external content
    right: |
      This book was built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - part: process.qmd
      chapters:
        - prep-data.qmd
        - model.qmd
    - software.qmd
    - organize.qmd
    - references.qmd
  appendices:
    - glossary.qmd
    - part: explorations.qmd
      chapters:
        - explorations/am-fine.qmd


# website:
#   title: "MarineSDMs"
#   repo-url: https://github.com/marinebon/sdm-book
#   reader-mode: true
#   repo-actions: [edit]
#   search: true
#   google-analytics: "G-V3HZN14Z8G"
#   page-navigation: true
#   sidebar:
#     style: "docked"
#     search: true
#     contents:
#       - overview.qmd
#       - section: "Process"
#         contents:
#           - prep-data.qmd
#           - model.qmd
#       - text: "---"
#       - explorations.qmd
#       - glossary.qmd

bibliography: references.bib

filters:
 - lightbox
lightbox: auto

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    mermaid:
      theme: neutral
    theme:
      light: flatly
      dark: darkly
    css: glossary.css
  pdf:
    documentclass: scrreprt
  docx: default
    # reference-doc: custom-reference.docx

editor: visual

