project:
  type: book
  output-dir: _book
  resources:
    - /.nojekyll

book:
  title: "MarineSDMs"
  subtitle: "Marine Species Distribution Models"
  author: "Ben Best"
  repo-url: https://github.com/marinebon/sdm-book
  reader-mode: true
  repo-actions: [edit]
  downloads: [pdf, docx]
  sharing: [twitter, facebook]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  google-analytics: "G-V3HZN14Z8G"
  page-navigation: true
  page-footer:
    left: |
      © [Ben Best](https://bbest.github.io/cv/)
    right: |
      Built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - part: process.qmd
      chapters:
        - prep-data.qmd
        - model.qmd
        - mosaic.qmd
    - software.qmd
    - organize.qmd
    - references.qmd
  appendices:
    - glossary.qmd
    - part: explorations.qmd
      chapters:
        - explorations/am-fine.qmd

bibliography: references.bib

filters:
 - lightbox
lightbox: auto

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    mermaid:
      theme: neutral
    theme:
      light: flatly
      dark: darkly
    css: glossary.css
  pdf:
    documentclass: scrreprt
  docx: default

editor: visual

