project:
  type: book
  output-dir: _book
  resources:
    - /.nojekyll

book:
  title: "MarineSDMs"
  subtitle: "Marine Species Distribution Models"
  author:
  - name: Benjamin D. Best
    orcid: 0000-0002-2686-0784
    email: ben@ecoquants.com
    affiliations:
      - name: EcoQuants LLC
        address: 211 W Gutierrez St, Unit 12
        city: Santa Barbara
        state: CA
        postal-code: 93101
      - name: MarineBON
  repo-url: https://github.com/marinebon/sdm-book
  reader-mode: true
  repo-actions: [edit]
  downloads: [pdf, docx]
  sharing: [twitter, facebook]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  google-analytics: "G-V3HZN14Z8G"
  page-navigation: true
  page-footer:
    left: |
      © <a href="https://bbest.github.io/cv/"  target="_blank">Ben Best</a>, <a href="https://marinebon.org"  target="_blank">MarineBON</a>
    right: |
      Built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - part: "Prepare"
      chapters:
        - prep.qmd
        - occ.qmd
        - abs.qmd
        - env.qmd
    - part: "Model"
      chapters:
        - model.qmd
        - split.qmd
        - fit.qmd
        - calibrate.qmd
        - predict.qmd
        - evaluate.qmd
    - part: "Combine"
      chapters:
        - combine.qmd
        - ensemble.qmd
        - mosaic.qmd
        - taxa.qmd
        - indicators.qmd
    - part: "Share"
      chapters:
        - share.qmd
        - metadata.qmd
        - portal.qmd
    - references.qmd
  appendices:
    - glossary.qmd
    - part: explorations.qmd
      chapters:
        - explorations/am-fine.qmd
        - explorations/am-envelope.qmd
        - "explorations/sdm-1_predicts.qmd"
        - "explorations/obis-top-spp-by-class.qmd"
    # - organize.qmd
    - software.qmd

bibliography: references.bib

filters:
 - lightbox
lightbox: auto

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    mermaid:
      theme: neutral
    theme:
      light: flatly
      dark: darkly
    css: glossary/glossary.css
  pdf:
    documentclass: scrreprt
    keep-tex: true
  docx: default

editor: visual

