# Introduction

```{r}
#| echo: false
#| eval: false

# in .Rprofile:
if (!"glossary" %in% rownames(installed.packages()))
  install.packages(
    "glossary",
    repos = c(
      "https://debruine.r-universe.dev",
      "https://cloud.r-project.org"))
library(glossary)
glossary::glossary_path("glossary/glossary.yml")
glossary::glossary_popup("click")
glossary::glossary_persistent("glossary/glossary-persistent.yml")
# Terminal: quarto publish gh-pages
```

## Background

The best available global distributions are presently AquaMaps [@kaschner2006; @ready2010] with supplementation by IUCN RedList range maps[^index-1]. These have been used to calculate the biodiversity within national waters [@halpern2012] as well as beyond in the high seas [@visalli2020].

[^index-1]: IUCN RedList range maps: <https://www.iucnredlist.org/resources/spatial-data-download>

## Goals

This book aims to capture the overview and details of modeling species distributions in the marine environment for the purposes of advancing the status quo of global and U.S. national species distributions along the following dimensions:

1.  **Space**\
    The current AquaMaps distributions are ${1}/{2}$ยบ (\~55 km at equator), whereas the best available global bathymetry is ${1}/{240}$ยบ (\< 0.5 km).

2.  **Time**\
    The current AquaMaps distributions are based on static climatic averages over all seasons, which does not capture temporal dynamics: seasonally within a year, nor long-term climate change trends. This will necessitate sampling the environment contemporaneously with species observations before fitting the model and predicting to different environmental snapshots.

3.  **Environment**\
    Other environmental variables besides the initial physiographic (depth) and oceanographic (temperature, chlorophyll, primary productivity and ice) may elicit an improved statistical fit, related to species' environmental niche. Some candidates include: temperature fronts, eddy kinetic energy, distance from shore, distance from shelf.

4.  **Biology**\
    Where sufficient observations exist, additional models should be developed highlighting differences between:

    -   **Life stage**, e.g. larval vs adult.

    -   **Gender** where varies, such as male sperm whales being more cosmopolitan.

    -   **Subpopulations** for understanding metapopulation dynamics

    -   **Behavior**, such as migrating, feeding or breeding.

By definition `r glossary("MBON")` is a network, so this is inclusive of and meant for all participants.

## Motivations

-   [AquaMaps.org](https://aquamaps.org/)\
    AquaMaps [@kaschner2006; @ready2010] represents a massive amount of work to gather parameters for \>33.5K marine species, including areas to mask out.

-   [OBIS.org](OBIS.org)\
    The Ocean Biogeographic Information System [@klein2019; @grassle2000]is the central portal for continuously added observations with extra flags for quality control, all of which makes marine SDMs possible.

-   **Modeling** methods have dramatically improved over time and are ripe for fresh application. The R package `dismo` originally came came out with an [SDM vignette](https://cran.r-project.org/web/packages/dismo/vignettes/sdm.pdf) as a practical supplement to their excellent review of SDMs [@elith2009] and using the Maxent algorithm [@elith2011]. The raster package furthered that (raster[sdm](https://rspatial.org/raster/sdm/)) and now there's [`terra` sdm](https://rspatial.org/sdm/). Alongside these developments has been a boon of cloud-computing, particularly Google Earth Engine [@gorelick2017; @camposEcologicalNicheModels2023], allowing for dense global raster processing.

-   The world is quickly moving towards a future trying to conserve 30% of the oceans by 2030, so called "[**30 by 30**](https://en.wikipedia.org/wiki/30_by_30)". In the U.S., this is [America the Beautiful](https://www.noaa.gov/america-the-beautiful) initiative. We need biodiversity indicators to track progress. This push for conservation is driven by increasing impacts of **climate change**, as evidenced by marine heatwaves and shifts in population distributions.

## Contribute

We very much welcome your feedback, contributions and collaboration. Here are a few ways from least to most involved:

1.  Email Ben (ben\@ecoquants.com) with any suggestions, including suggested revisions of this online book.

    ::: callout-note
    Note that you can download this entire book as:

    -   {{< fa file-pdf >}} Adobe Acrobat [pdf](https://marinebon.github.io/MarineSDMs/MarineSDMs.pdf) to add annotations; or

    -   {{< fa file-word >}} Microsoft Word [docx](https://marinebon.github.io/MarineSDMs/MarineSDMs.docx) to edit with Track Changes on.

    These are available in the upper left navigation menu by clicking the download icon <i class="bi bi-download"></i>.
    :::

2.  Submit a [New Issue](https://github.com/marinebon/MarineSDMs/issues/new/choose) on Github.

3.  Click on "<i class="bi bi-github"></i> Edit this Page" in the upper right. If you have a Github account, then you can fork this repository from owner "marinebon" to your username, edit the page(s) and submit a pull request.

4.  If you are a regular contributor, you can be added to the collaborators of this repository to push changes directly (without needing a pull request).

## Features of this Book

-   Multiple formats\
    From the singe set of source Quarto documents (\*.qmd), several output formats are rendered: html, pdf, docx. This is particularly helpful when suggesting changes. It also lends itself well to being carved into manuscripts.

-   Self-rendering\
    Github hosts the web pages (\*.html), which get rendered from the source code (\*.qmd) using a Github Action. So edits can be made simply through the web interface and all outputs get updated (html, pdf, docx). It also ensures the reproducibility of the document with a common setup environment.

-   Mermaid diagrams

-   Quarto document listings

-   References

-   Glossary

-   Search
