# Organize

## Partners

-   ***Confirmed***

    -   [AquaMaps](https://www.aquamaps.org/)\
        *distribution maps for over 33,500 species of fishes, marine mammals and invertebrates*

        -   Gabriel Reygondeau (g.reygondeau\@oceans.ubc.ca)

    -   [MBON](https://marinebon.org/)\
        *Marine Biodiversity Observation Network (NOAA, NASA)*

        -   Ben Best

        -   Tylar Murray

        -   Dan Otis

        -   Frank Muller-Karger

    -   [OBIS](https://obis.org/)**\
        ***Ocean Biodiversity Information System (UNESCO)*

        -   Candido Principe De Souza, Silas (s.principe\@unesco.org)

        -   Ward Appeltans (w.appeltans\@unesco.org)

-   ***Proposed***

    -   [DisMAP](https://apps-st.fisheries.noaa.gov/dismap/)\
        *Distribution Mapping and Analysis Portal (NOAA)*

        -   Melissa Karp (melissa.karp\@noaa.gov)

        -   Roger Griffis (roger.b.griffis\@noaa.gov)

    -   [FishBase](https://www.fishbase.org.au/v4)\
        *global species database of fish species (also: Sea Around Us / Sea Life Base)*

        -   Deng Palomares

        -   Kathleen Reyes

    -   [FishGLOB](https://fishglob.sites.ucsc.edu/)\
        *Fish biodiversity under global change (global bottom trawl)*

        -   Malin Pinsky

    -   [Lenfest Marine Biodiversity Dialogues](https://www.lenfestocean.org/en/research-projects/marine-biodiversity-dialogues-task-force-i)\
        *developing a framework to assess the abundance and distribution of marine biodiversity in U.S. (Smithsonian, U of Queensland)*

        -   Daniel Dunn

        -   Emmett Duffy

    -   [MGEL](https://mgel.env.duke.edu/)\
        *Marine Geospatial Ecology Lab (Duke)*

        -   Jason Roberts

        -   Patrick Halpin

    -   [MPA-Europe](https://mpa-europe.eu/)

        -   Mark Costello

    -   [Natura Connect](http://www.maraujolab.eu/inaugural-session-of-natura-connect-pt-think-thank/)\
        *Think Tank within the Natura Connect to discuss the implementation of the European Biodiversity Strategy in Portugal*

        -   Miguel Araujo\

    -   [NCEAS](https://www.nceas.ucsb.edu/)\
        *National Center for Ecological Analysis and Synthesis*

        -   Casey O'Hara

        -   Ben Halpern\

    -   [PMEL](https://www.pmel.noaa.gov/)\
        *Pacific Marine Environmental Lab (NOAA)*

        -   Heather Welch

        -   Elliot Hazen

    -   [Wallace](https://wallaceecomod.github.io)\
        *Shiny web interface (terrestrial so far) for creating SDMs (AMNH)*

        -   Jamie Kass

        -   Mary Blair

## Timeline

### Meetings

-   **2024-01-23**\
    Marine Biodiversity Summit in DC\
    (organized by Gabrielle, Emmett)

-   **2024-03-21**\
    SDM meeting in New Orleans\
    (organized by BDB; so far AquaMaps)

### Sequence

1.  
